### ISSUE TITLE
index.html not compressed when served from "/" and EncodedOnInit is set 

### ISSUE THREAD

**Issue by icellan** [vearutop/statigz#15]
Love this package! Very easy to use and a great help.

I noticed that when you turn on `EncodeOnInit` the assets you would expect are compressed, except for the index.html when served from `/`.

**Comment by vearutop** [comment]
Hello, thank you for using this library!

There are [two hardcoded constraints](https://github.com/vearutop/statigz/blob/v1.1.7/server.go#L54-L57) 
```go
	// minSizeToEncode is minimal file size to apply encoding in runtime, 1KiB.
	minSizeToEncode = 1024

	// minCompressionRatio is a minimal compression ratio to serve encoded data, 97%.
	minCompressionRatio = 0.97
```
that may have filtered out a small or non-compressible `index.html`.

I just checked with another `index.html` and got it compressed in response.
(easy to check by suffix on e-tag header, e.g. `Etag: 37o27d4dxa6y5.gz`)

**Comment by icellan** [comment]
Any chance of being able to change those?

Thanks!

**Comment by vearutop** [comment]
Why would you compress something that is already small?

**Comment by icellan** [comment]
Good question. Maybe over-optimizing.

I had an index.html that was 970 bytes and was seeing if it could be even smaller, especially on mobiles.

**Comment by vearutop** [comment]
There is a belief that "Compressing assets smaller than 1400 bytes is pointless", I'm not sure if that is really the case, but seems reasonable.

Though asset comes with headers that can easily add 200-500 bytes to the packet, so maybe the compression would be helpful to balance large headers (e.g. 900 bytes of headers and 500 bytes of compressed content).

https://webmasters.stackexchange.com/a/89958
https://www.computerworld.com/article/2693941/why-it-doesn-t-make-sense-to-gzip-all-content-from-your-web-server.html

Maybe it makes sense to lower the threshold to something around 700 bytes to optimize for case with large headers.

**Comment by icellan** [comment]
I would vote for lowering it and making it configurable, just like `EncodeOnInit`.

**Comment by vearutop** [comment]
I've reduced min size to 512 (without adding manual control to avoid complexity) in latest version, hopefully that will be good enough for majority of practical cases.
