### ISSUE TITLE
SPA support?

### ISSUE THREAD

**Issue by davidspiess** [vearutop/statigz#17]
I am developing a single page application and would like to use client side routing.
If a static resource was not found it should always return the content of the index.html.
Would this functionality be possible to add?

**Comment by vearutop** [comment]
Technically, such functionality can be implemented on top of the library with middleware (no need for specific in-library support).

However, this whole scenario sounds weird to me. Are you sure `/missing-script.js` should result with `200 OK` and `text/html` content type? (I'd expect client side routing to properly process relevant HTTP statuses)

**Comment by vearutop** [comment]
I've updated the library to make middleware simpler (to avoid wrapping and capturing response writer).
https://github.com/vearutop/statigz#custom-handling-of-not-found

This is how you can implement such middleware now.
```go
fileServer := statigz.FileServer(st)
customHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    // Serve existing static resource.
    if fileServer.Found(r) {
        fileServer.ServeHTTP(w, r)

        return
    }

    // Do something custom for non-existing resource, for example serve index page.
    // (This is an example, serving index instead of 404 might not be the best idea in real life 😅).
    r.URL.Path = "/"
    fileServer.ServeHTTP(w, r)
})

// Plug static assets handler to your server or router.
if err := http.ListenAndServe("localhost:80", customHandler); err != nil {
    log.Fatal(err)
}
```

**Comment by davidspiess** [comment]
Thank you very much, this is a very clean solution and works flawlessly.
