### ISSUE TITLE
Feature suggestion: OnNotFound handler

### ISSUE THREAD

**Issue by astrolox** [vearutop/statigz#19]
Thank you for creating this package. It is exactly what I was looking for when updating an old project which was using [`vfsgen`](https://github.com/shurcooL/vfsgen) and [`httpgzip`](https://github.com/shurcooL/httpgzip).

I see [the example you've provided for how to change the 404 behaviour](https://github.com/vearutop/statigz/blob/master/server_test.go#L357). However I am concerned at that approach requires that the logic to find a file is run twice for each request.

I know it's not a lot of overhead, but I was wondering if you'd be open to the idea of adding a `OnNotFound` handler similar to the `OnError` handler that already exists. Obviously replacing the [call to `http.NotFound` on line 367](https://github.com/vearutop/statigz/blob/master/server.go#L367) with a call to `OnNotFound` instead.

The benefit being that having a custom not found handler in your app only incurs extra overhead during the not found requests.

**Comment by vearutop** [comment]
Thank you, I think this is a good idea.

If you could make a PR, that would be great, otherwise I'll try to work on this some time later.

**Comment by vearutop** [comment]
Closed in #20.
