### ISSUE TITLE
Using this library with fs.Sub

### ISSUE THREAD

**Issue by s00500** [vearutop/statigz#7]
I am trying to use this library with fs.Sub as my assets are in a subfolder. 
But this library requires fs.ReadDirFS

Is there any better approach that I do not know off or are changes to the library required ?

Greetings

**Comment by vearutop** [comment]
Type assertion should work, please check the example.

```go
//go:embed _testdata/*
var st embed.FS

func ExampleFileServer() {
	s, err := fs.Sub(st, "_testdata")
	if err != nil {
		log.Fatal(err)
	}

	// Plug static assets handler to your server or router.
	err = http.ListenAndServe(":80", statigz.FileServer(s.(fs.ReadDirFS), brotli.AddEncoding))
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by s00500** [comment]
Right, it does, just got it working a minute ago, thanks for the quick answer :-)
