### ISSUE TITLE
Serving index.html

### ISSUE THREAD

**Issue by asmaloney** [vearutop/statigz#9]
It doesn't look like statigz is serving `index.html` properly when it's left off the URL. (I am using the *Mounting a subdirectory* option from the README in case that's an issue.)

e.g. `http://localhost/` should be serving index.html, but it's not.

`http.FileServer` will serve this properly.

In fact, it says in the http.FileServer docs:

> As a special case, the returned file server redirects any request ending in "/index.html" to the same path, without the final "index.html".

...and then the code serving the files in [http/fs.go](https://github.com/golang/go/blob/ad97d204f02c1f9ad0433e9178d6ce0f3fdb1f9f/src/net/http/fs.go#L586) has some checks to default to index.html in a dir.

It would be useful for statigz to handle this the same way so it can be a drop-in replacement.

Thanks!

**Comment by vearutop** [comment]
Good catch! Let me check what I can do to align behaviors.

**Comment by vearutop** [comment]
@asmaloney please check if the new `v1.1.5` works well for you.

**Comment by asmaloney** [comment]
Works great - thanks Viacheslav.

And thanks for this package - nice and simple to use! 🎆
